<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Featured', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1170},"gap":"no","elementId":"guten-emzJz5","background":{"type":"default","color":{"type":"variable","id":"gv-color-black"},"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"zIndex":{"Desktop":"1"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-loDB2a","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-background-primary"}}},"borderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Mobile":{"unit":"px","dimension":{"right":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-LGzmd2","icon":"far fa-paper-plane","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE2LjEgMjYwLjJjLTIyLjYgMTIuOS0yMC41IDQ3LjMgMy42IDU3LjNMMTYwIDM3NlY0NzkuM2MwIDE4LjEgMTQuNiAzMi43IDMyLjcgMzIuN2M5LjcgMCAxOC45LTQuMyAyNS4xLTExLjhsNjItNzQuMyAxMjMuOSA1MS42YzE4LjkgNy45IDQwLjgtNC41IDQzLjktMjQuN2w2NC00MTZjMS45LTEyLjEtMy40LTI0LjMtMTMuNS0zMS4ycy0yMy4zLTcuNS0zNC0xLjRsLTQ0OCAyNTZ6bTUyLjEgMjUuNUw0MDkuNyA5MC42IDE5MC4xIDMzNmwxLjIgMUw2OC4yIDI4NS43ek00MDMuMyA0MjUuNEwyMzYuNyAzNTUuOSA0NTAuOCAxMTYuNiA0MDMuMyA0MjUuNHoiLz48L3N2Zz4=","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"45","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-Bqklwi","content":"Future Concept.","color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"28"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-56uTi2","width":{"Desktop":"24"},"dividerColor":{"type":"variable","id":"gv-color-dark-primary"},"size":{"Desktop":"2.5"},"dividerAlign":{"Desktop":"left"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-pVdki2","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-TnUX08","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-background-primary"}}},"borderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-2P4hOq","icon":"fas fa-globe","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTM1MiAyNTZjMCAyMi4yLTEuMiA0My42LTMuMyA2NEgxNjMuM2MtMi4yLTIwLjQtMy4zLTQxLjgtMy4zLTY0czEuMi00My42IDMuMy02NEgzNDguN2MyLjIgMjAuNCAzLjMgNDEuOCAzLjMgNjR6bTI4LjgtNjRINTAzLjljNS4zIDIwLjUgOC4xIDQxLjkgOC4xIDY0cy0yLjggNDMuNS04LjEgNjRIMzgwLjhjMi4xLTIwLjYgMy4yLTQyIDMuMi02NHMtMS4xLTQzLjQtMy4yLTY0em0xMTIuNi0zMkgzNzYuN2MtMTAtNjMuOS0yOS44LTExNy40LTU1LjMtMTUxLjZjNzguMyAyMC43IDE0MiA3Ny41IDE3MS45IDE1MS42em0tMTQ5LjEgMEgxNjcuN2M2LjEtMzYuNCAxNS41LTY4LjYgMjctOTQuN2MxMC41LTIzLjYgMjIuMi00MC43IDMzLjUtNTEuNUMyMzkuNCAzLjIgMjQ4LjcgMCAyNTYgMHMxNi42IDMuMiAyNy44IDEzLjhjMTEuMyAxMC44IDIzIDI3LjkgMzMuNSA1MS41YzExLjYgMjYgMjAuOSA1OC4yIDI3IDk0Ljd6bS0yMDkgMEgxOC42QzQ4LjYgODUuOSAxMTIuMiAyOS4xIDE5MC42IDguNEMxNjUuMSA0Mi42IDE0NS4zIDk2LjEgMTM1LjMgMTYwek04LjEgMTkySDEzMS4yYy0yLjEgMjAuNi0zLjIgNDItMy4yIDY0czEuMSA0My40IDMuMiA2NEg4LjFDMi44IDI5OS41IDAgMjc4LjEgMCAyNTZzMi44LTQzLjUgOC4xLTY0ek0xOTQuNyA0NDYuNmMtMTEuNi0yNi0yMC45LTU4LjItMjctOTQuNkgzNDQuM2MtNi4xIDM2LjQtMTUuNSA2OC42LTI3IDk0LjZjLTEwLjUgMjMuNi0yMi4yIDQwLjctMzMuNSA1MS41QzI3Mi42IDUwOC44IDI2My4zIDUxMiAyNTYgNTEycy0xNi42LTMuMi0yNy44LTEzLjhjLTExLjMtMTAuOC0yMy0yNy45LTMzLjUtNTEuNXpNMTM1LjMgMzUyYzEwIDYzLjkgMjkuOCAxMTcuNCA1NS4zIDE1MS42QzExMi4yIDQ4Mi45IDQ4LjYgNDI2LjEgMTguNiAzNTJIMTM1LjN6bTM1OC4xIDBjLTMwIDc0LjEtOTMuNiAxMzAuOS0xNzEuOSAxNTEuNmMyNS41LTM0LjIgNDUuMi04Ny43IDU1LjMtMTUxLjZINDkzLjR6Ii8+PC9zdmc+","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"50","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-liNS9O","content":"The Big Ideas.","color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"28"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-qAC51u","width":{"Desktop":"24"},"dividerColor":{"type":"variable","id":"gv-color-dark-primary"},"size":{"Desktop":"2.5"},"dividerAlign":{"Desktop":"left"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-DFegyi","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-LfRBuX","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"border":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-background-primary"}}},"borderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-primary"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"40","bottom":"50","left":"40"}},"Mobile":[]},"animation":{"type":{"Desktop":"slideInUp"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-FhRpI6","icon":"fas fa-lightbulb","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzODQgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTI3MiAzODRjOS42LTMxLjkgMjkuNS01OS4xIDQ5LjItODYuMmwwIDBjNS4yLTcuMSAxMC40LTE0LjIgMTUuNC0yMS40YzE5LjgtMjguNSAzMS40LTYzIDMxLjQtMTAwLjNDMzY4IDc4LjggMjg5LjIgMCAxOTIgMFMxNiA3OC44IDE2IDE3NmMwIDM3LjMgMTEuNiA3MS45IDMxLjQgMTAwLjNjNSA3LjIgMTAuMiAxNC4zIDE1LjQgMjEuNGwwIDBjMTkuOCAyNy4xIDM5LjcgNTQuNCA0OS4yIDg2LjJIMjcyek0xOTIgNTEyYzQ0LjIgMCA4MC0zNS44IDgwLTgwVjQxNkgxMTJ2MTZjMCA0NC4yIDM1LjggODAgODAgODB6TTExMiAxNzZjMCA4LjgtNy4yIDE2LTE2IDE2cy0xNi03LjItMTYtMTZjMC02MS45IDUwLjEtMTEyIDExMi0xMTJjOC44IDAgMTYgNy4yIDE2IDE2cy03LjIgMTYtMTYgMTZjLTQ0LjIgMC04MCAzNS44LTgwIDgweiIvPjwvc3ZnPg==","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"50","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-dark-primary"},"background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-BnaBoM","content":"Creative Solutions.","color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"28"},"Mobile":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-CKrMwL","width":{"Desktop":"24"},"dividerColor":{"type":"variable","id":"gv-color-dark-primary"},"size":{"Desktop":"2.5"},"dividerAlign":{"Desktop":"left"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-aSob44","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"width":{"Desktop":1170},"gap":"no","elementId":"guten-tecoV4","background":{"type":"default","color":{"type":"variable","id":"black"},"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"80"}},"Mobile":{"unit":"px","dimension":{"bottom":"40","top":"","right":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"slow","delay":"1400"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-TfCqLS","border":{"right":{"type":"solid","width":"3","color":{"type":"variable","id":"gv-color-dark-primary"}},"radius":{"Desktop":[]}},"margin":{"Mobile":[],"Desktop":[]},"padding":{"Mobile":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"slow","delay":""}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-ZcLJy5","space":{"Desktop":{"point":"60","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-SwnVsl","border":{"radius":{"Desktop":[]}}} /-->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
