<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Services', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1170},"elementId":"guten-0xMmj4","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-secondary"},"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"none"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-JYItSA"} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-2vPIkr"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-UNqA2e"} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-h2bOdg","alignText":{"Desktop":"flex-start"},"text":"Services","focusText":"","subText":"Our Services For Clients","lineWidth":{"Desktop":{"unit":"px"},"Tablet":"","Mobile":""},"lineHeight":{"Desktop":"3"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainBackground":{"type":"default","gradientColor":[{"color":"rgb(49, 207, 180)","id":1,"offset":"0.132","active":true},{"color":"rgb(126, 32, 207)","id":2,"offset":"1.000","active":false}],"color":""},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","top":""}},"Mobile":[],"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"focusBackground":{"type":"default","color":""},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"focusPadding":{"Desktop":{"unit":"px","dimension":{"top":"3","right":"3","bottom":"3","left":"3"}}},"subColor":{"type":"variable","id":"gv-color-dark-primary"},"subTypography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"uppercase","spacing":{"Desktop":"0.01"},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"lineColor":{"type":"variable","id":"gv-color-dark-primary"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-P6UnbT","hideMobile":true} /-->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-2tdPSp","border":{"radius":{"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"60"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Mobile":null},"elementId":"guten-kcvFCs","margin":{"Desktop":{"unit":"px","dimension":{"right":"20","bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-ScoKgT","separateButtonLink":false,"title":"Digital Strategy","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id arcu luctus.","icon":"gtn gtn-chart2-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-primary"}}},"iconPadding":{"Desktop":[],"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"},"parentSelector":".guten-ScoKgT:hover .guten-icon-box-wrapper","imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Mobile":null},"elementId":"guten-QNXeT8","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"","top":"","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-QDOrez","separateButtonLink":false,"title":"UI Designs","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id arcu luctus.","icon":"gtn gtn-design-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-dark-primary"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"r":255,"g":255,"b":255,"a":1}}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"gv-color-dark-background-primary"},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Tablet":[]},"titleColor":{"type":"variable","id":"gv-color-dark-background-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-dark-background-primary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"parentSelector":".guten-QDOrez:hover .guten-icon-box-wrapper","imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.4,"Mobile":null},"elementId":"guten-EJrIPk","margin":{"Desktop":{"unit":"px","dimension":{"right":"0","bottom":"","top":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-M5k1eR","separateButtonLink":false,"title":"Content Writing","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id arcu luctus.","icon":"gtn gtn-Profile-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-primary"}}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[]},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"titlePadding":{"Desktop":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Tablet":[]},"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"parentSelector":".guten-M5k1eR:hover .guten-icon-box-wrapper","imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-B6kidw","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Mobile":null},"elementId":"guten-QoUh0Q","margin":{"Desktop":{"unit":"px","dimension":{"right":"20","bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-OQNpDS","separateButtonLink":false,"title":"Marketing Strategy","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id arcu luctus.","icon":"gtn gtn-coins-1-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-primary"}}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Tablet":[]},"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"},"parentSelector":".guten-OQNpDS:hover .guten-icon-box-wrapper","imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Mobile":null},"elementId":"guten-PQV5DZ","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"","top":"","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-TQByUv","separateButtonLink":false,"title":"Web Development","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id arcu luctus.","icon":"gtn gtn-code-solid","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-primary"}}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Tablet":[]},"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"},"parentSelector":".guten-TQByUv:hover .guten-icon-box-wrapper","imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.4,"Mobile":null},"elementId":"guten-ZtyTR2","margin":{"Desktop":{"unit":"px","dimension":{"right":"0","bottom":"","top":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/icon-box {"elementId":"guten-aAEOZW","separateButtonLink":false,"title":"Social Media","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id arcu luctus.","icon":"gtn gtn-social-share-light","iconSize":{"Desktop":"40"},"align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-black"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-text-primary"}}},"containerBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"bottom":{"type":"solid","width":"5","color":{"type":"variable","id":"gv-color-dark-primary"}}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"iconColor":{"type":"variable","id":"gv-color-dark-primary"},"iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Tablet":[]},"titleColor":{"type":"variable","id":"gv-color-dark-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"},"parentSelector":".guten-aAEOZW:hover .guten-icon-box-wrapper","imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
