<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1170,"Tablet":""},"elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":154,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/achievement-agreement-arms-bump-business-cheerful-1456477-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-primary"}},"opacity":"0.8","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"300","bottom":"300"}},"Tablet":{"unit":"px","dimension":{"top":"220","bottom":"120"}},"Mobile":{"unit":"px","dimension":{"top":"160","bottom":"80","right":"10","left":"10"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-hPOdgn","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-a33bDf","content":"404","type":1,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"404-font","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"156"},"Mobile":{"unit":"px","point":"56"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-20"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-CyvafI","content":"Page Not Found","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Mobile":{"unit":"px","dimension":{"top":""}},"Desktop":[]},"padding":{"Mobile":[]}} /-->

<!-- wp:gutenverse/divider {"elementId":"guten-yot7AV","width":{"Desktop":"10","Mobile":"20"},"dividerColor":{"type":"variable","id":"gv-color-dark-primary"},"size":{"Desktop":"4"},"gap":{"Desktop":"0"},"dividerAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"2","bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/search {"elementId":"guten-0wGA2v","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"120","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Tablet":{"unit":"px"}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-dark-text-placeholder"}},"inputPlaceholder":"Search here...","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"inputHeight":{"Desktop":"56","Tablet":""},"inputWidth":{"Desktop":{"point":"480","unit":"px"},"Mobile":{"unit":"%","point":"100"},"Tablet":{"unit":"px"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-dark-background-primary"}},"inputBorderNormal":{"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"gv-color-dark-text-primary"}},"alignContent":{"Desktop":"center"}} -->
<!-- wp:gutenverse/button {"elementId":"guten-tx7wYf","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Desktop":"100"},"buttonBackground":{"color":{"type":"variable","id":"gv-color-dark-primary"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-dark-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10"}}},"color":{"type":"variable","id":"gv-color-dark-background-primary"},"iconColor":{"type":"variable","id":"gv-color-dark-background-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"500"},"hoverIconColor":{"type":"variable","id":"gv-color-dark-background-primary"},"hoverTextColor":{"type":"variable","id":"gv-color-dark-background-primary"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
