<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Hero', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1170,"Mobile":""},"elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":40,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/background.webp","width":1920,"height":1280,"altOriginal":""}},"position":{"Desktop":"top center","Tablet":"center center"},"size":{"Desktop":"custom","Tablet":"cover"},"repeat":{"Desktop":"no-repeat"},"yposition":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"200","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"},"Tablet":{"unit":"px","point":"100"}},"width":{"Desktop":{"unit":"%","point":"85"},"Tablet":{"unit":"%","point":"100"}},"color":{"type":"variable","id":"black"},"videoPlayOnMobile":false,"fetchPriorityHigh":true},"backgroundOverlay":{"type":"default","color":"","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270},"opacity":"0.1","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"300","bottom":"180"}},"Tablet":{"unit":"px","dimension":{"top":"220","bottom":"120","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"220","top":"300"}}},"zIndex":{"Desktop":"2"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":55.99,"Tablet":68},"elementId":"guten-91Fk0O","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-0iCbAc","textColor":{"r":194,"g":186,"b":176,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"80","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-CqbjQ5","content":"CREATIVE MIND, CREATIVE WORKS.","color":{"type":"variable","id":"gv-color-dark-primary"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"uppercase","spacing":{"Desktop":"0.01"},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-XvGz0E","content":"We Are Digital Agency","type":1,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"76"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"containsAnchorTag":false,"background":{"type":"default"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"Getting Started","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"23","right":"30","bottom":"23","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"18","bottom":"18"}}},"buttonBackground":{"type":"default","color":{"r":145,"g":108,"b":61,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-primary"}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":2,"color":{"type":"variable","id":"gv-color-dark-accent-hover"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"60"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"transform":"uppercase","spacing":{"Desktop":"0.1"},"weight":"500"},"hoverTextColor":{"type":"variable","id":"gv-color-dark-text-primary"},"ariaLabel":"Direct to Contact"} /-->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":44.01,"Tablet":null,"Mobile":null},"elementId":"guten-lpET5f","hideMobile":true} /-->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
