<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse About', 'zeever' ),
	'categories' => array( 'zeever-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1170},"elementId":"guten-Dprc0W","background":{"type":"default","color":{"type":"variable","id":"gv-color-black"},"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","left":"10","right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"20"}}},"animation":{"type":{"Desktop":"none"}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-j6ojyR","border":{"radius":{"Desktop":[]}}} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-sK0EZN"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-UyU4sb"} -->
<!-- wp:gutenverse/advanced-heading {"elementId":"guten-yelKpQ","alignText":{"Desktop":"flex-start"},"text":"About","focusText":"","subText":"We Are Best Digital Agency Since 2008","lineWidth":{"Desktop":{"unit":"px"},"Tablet":"","Mobile":""},"lineHeight":{"Desktop":"3"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"mainColor":{"type":"variable","id":"gv-color-dark-text-primary"},"mainTypography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"48"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"mainBackground":{"type":"default","gradientColor":[{"color":"rgb(49, 207, 180)","id":1,"offset":"0.132","active":true},{"color":"rgb(126, 32, 207)","id":2,"offset":"1.000","active":false}],"color":""},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":"","top":""}},"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"focusBackground":{"type":"default","color":""},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"focusPadding":{"Desktop":{"unit":"px","dimension":{"top":"3","right":"3","bottom":"3","left":"3"}}},"subColor":{"type":"variable","id":"gv-color-dark-primary"},"subTypography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"transform":"uppercase","spacing":{"Desktop":"0.01"},"weight":"500"},"subMargin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":[]},"subPadding":{"Desktop":[],"Mobile":[]},"lineColor":{"type":"variable","id":"gv-color-dark-primary"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-dBWwNb","hideMobile":true} /-->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-vLJh6x","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-cO6xEN","background":{"type":"default","image":{"Desktop":{"id":98,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/employee-meeting-work-job-working-argentina-1599048-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"color":""},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"zeever-third"},"image":{"Desktop":[]},"size":{"Desktop":"cover"},"position":{"Desktop":"center center"},"gradientColor":[{"color":"rgba(10, 10, 10, 0.94)","opacity":0.94,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"0"},"opacity":"0.3","backgroundOverlayHover":{"type":"default","color":{"type":"variable","id":"black"}},"opacityHover":"0.6","margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"30","bottom":"20"}},"Mobile":[]}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-FQELbH","space":{"Desktop":{"point":"488","unit":"px"},"Mobile":{"point":"220","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-B7JdHF","content":"Team Work","type":3,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-SG5vxS","content":"Committed and creative","type":6,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"h6-font"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-8sM87L","backgroundOverlay":{"type":"default","color":""},"opacity":"","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Jly4gt","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":"","gradientColor":[{"color":"rgba(5, 5, 5, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(248, 248, 248, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"0"},"opacity":"","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","bottom":"","top":"","right":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-WGb1JH","background":{"type":"default","image":{"Desktop":{"id":99,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/employee-meeting-work-job-working-argentina-1599057-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"unit":"vh","point":"0"}},"xposition":{"Desktop":{"point":"0","unit":"px"}},"repeat":{"Desktop":"no-repeat"}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"zeever-third"}},"opacity":"0.1","backgroundOverlayHover":{"type":"default","color":{"type":"variable","id":"black"}},"opacityHover":"0.6","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":"30"}}}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-LvLr0V","space":{"Desktop":{"point":"180","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-BnSOfF","content":"Philosophy","type":3,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-yXt6c8","content":"Trust pays off","type":6,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"h6-font"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-AOAI9d","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":"","gradientColor":[{"color":"rgba(5, 5, 5, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(248, 248, 248, 0)","active":true,"opacity":0,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"0"},"opacity":"","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","bottom":"","top":"","right":""}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-WFRrcs","background":{"type":"default","image":{"Desktop":{"id":138,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/computer-group-building-home-internet-office-945774-pxhere.com_.webp"}},"position":{"Desktop":"center right"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"unit":"vh","point":"0"}},"xposition":{"Desktop":{"point":"0","unit":"px"}},"repeat":{"Desktop":"no-repeat"}},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"zeever-third"}},"opacity":"0.3","backgroundOverlayHover":{"type":"default","color":{"type":"variable","id":"black"}},"opacityHover":"0.6","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":"30"}}}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-SZoZ0M","space":{"Desktop":{"point":"180","unit":"px"}}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-seSbjd","content":"Office","type":3,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"22"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-QEAm6e","content":"Somewhere on earth","type":6,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"h6-font"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-fiToeQ","margin":{"Desktop":{"unit":"px","dimension":{"top":"80"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336},"elementId":"guten-FTsbXZ","margin":{"Desktop":{"unit":"px","dimension":{"right":"60"}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-3aYpzL","content":"Who We Are","type":4,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-pUn1hd","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":null},"elementId":"guten-AUdTnL","border":{"radius":{"Desktop":[],"Mobile":[]},"left":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-primary"}},"right":{"type":"solid","width":"2","color":{"type":"variable","id":"gv-color-dark-primary"}}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60","right":"30"}},"Tablet":{"unit":"px","dimension":{"left":"30"}},"Mobile":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-mTktAq","content":"Our Vision","type":4,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-JZDWvS","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-HSE8WK","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-14yMWh","content":"Our Mission","type":4,"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-bJ2nH4","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"15"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
